### ISSUE TITLE
Weblate - *.pot synchronization github stops working

### ISSUE THREAD

**Issue by sunwire** [rpm-software-management/dnf5#1892]
Weblate - *.pot synchronization github stops working.
The problem seems to be missing some Perl dependencies

```
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC entries checked: /usr/local/lib64/perl5/5.38 /usr/local/share/perl5/5.38 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at -e line 1.
CMake Error at test/perl5/CMakeLists.txt:14 (message):
  FindBin Perl module needed for tests was not found
```

**Comment by kontura** [comment]
Yes, the problem is that our `dnf-ci-host` build is failing: https://github.com/rpm-software-management/ci-dnf-stack/actions/workflows/ci-host.yml + there is a new dependency on `FindBin`.

The `dnf-ci-host` builds (and this issue) should be fixed by the next dnf5 rawhide release.

**Comment by sunwire** [comment]
Sync still not working, but for different reasons now/
https://github.com/rpm-software-management/dnf5/actions/runs/24274751559

**Comment by ppisar** [comment]
I think not working again. For new bugs please file new issues. Proposed fix is at #2686.
